### ISSUE TITLE
Dimensions

### ISSUE THREAD

**Issue by Chricky** [danielpierre/qlik-sense-dygraphs#2]
Hi there,

I found 2 issues with your wonderful dygraph extension:
1. There is no possibility to put letters/characters in Dimension place, only numbers
2. If you want 2 Dimensions, you HAVE to use 1 Date Field or it won't calculate it (right)

Regards
Chris

**Comment by danielpierre** [comment]
Hi Chris,

Thanks for bringing these concerns to my attention.  As for the first item, since this extension is built on top of the dygraphs library, which only accepts [numbers or dates](http://dygraphs.com/data.html) for x values, these are the only data types that may be used for the first dimension.  Regarding the second item, I've solved this problem in v2.0.1.

Best,
Daniel
